# Backend Dockerfile
# TODO: Configure backend container

FROM python:3.14-slim

WORKDIR /app

# COPY requirements.txt .
# RUN pip install -r requirements.txt

# COPY backend/ .

# CMD ["python", "main.py"]
